export interface Alunos {
  id: number;
  nome: string;
  idade: number;
  email: string;
  genero: string;
  classe: string;
  turno: string;
}

export const alunosMock: Alunos[] = [
  {
    id: 1,
    nome: "Lucas Silva",
    idade: 20,
    email: "lucas.silva@example.com",
    genero: "Masculino",
    classe: "1º Ano",
    turno: "Manhã",
  },
  {
    id: 2,
    nome: "Ana Costa",
    idade: 22,
    email: "ana.costa@example.com",
    genero: "Feminino",
    classe: "2º Ano",
    turno: "Tarde",
  },
  {
    id: 3,
    nome: "Carlos Oliveira",
    idade: 21,
    email: "carlos.oliveira@example.com",
    genero: "Masculino",
    classe: "3º Ano",
    turno: "Manhã",
  },
  {
    id: 4,
    nome: "Beatriz Almeida",
    idade: 23,
    email: "beatriz.almeida@example.com",
    genero: "Feminino",
    classe: "2º Ano",
    turno: "Noite",
  },
  {
    id: 5,
    nome: "Pedro Santos",
    idade: 19,
    email: "pedro.santos@example.com",
    genero: "Masculino",
    classe: "1º Ano",
    turno: "Tarde",
  },
  {
    id: 6,
    nome: "Mariana Pereira",
    idade: 22,
    email: "mariana.pereira@example.com",
    genero: "Feminino",
    classe: "3º Ano",
    turno: "Manhã",
  },
  {
    id: 7,
    nome: "Ricardo Souza",
    idade: 24,
    email: "ricardo.souza@example.com",
    genero: "Masculino",
    classe: "2º Ano",
    turno: "Noite",
  },
  {
    id: 8,
    nome: "Juliana Ribeiro",
    idade: 20,
    email: "juliana.ribeiro@example.com",
    genero: "Feminino",
    classe: "1º Ano",
    turno: "Manhã",
  },
  {
    id: 9,
    nome: "João Ferreira",
    idade: 25,
    email: "joao.ferreira@example.com",
    genero: "Masculino",
    classe: "3º Ano",
    turno: "Tarde",
  },
  {
    id: 10,
    nome: "Larissa Gomes",
    idade: 21,
    email: "larissa.gomes@example.com",
    genero: "Feminino",
    classe: "2º Ano",
    turno: "Manhã",
  },
  {
    id: 11,
    nome: "Gabriel Martins",
    idade: 23,
    email: "gabriel.martins@example.com",
    genero: "Masculino",
    classe: "1º Ano",
    turno: "Noite",
  },
  {
    id: 12,
    nome: "Vanessa Rocha",
    idade: 22,
    email: "vanessa.rocha@example.com",
    genero: "Feminino",
    classe: "3º Ano",
    turno: "Tarde",
  },
  {
    id: 13,
    nome: "Felipe Lima",
    idade: 19,
    email: "felipe.lima@example.com",
    genero: "Masculino",
    classe: "1º Ano",
    turno: "Manhã",
  },
  {
    id: 14,
    nome: "Paula Silva",
    idade: 20,
    email: "paula.silva@example.com",
    genero: "Feminino",
    classe: "2º Ano",
    turno: "Tarde",
  },
  {
    id: 15,
    nome: "Renato Costa",
    idade: 21,
    email: "renato.costa@example.com",
    genero: "Masculino",
    classe: "3º Ano",
    turno: "Noite",
  },
];
