export const salasMock = {
  "6° Ano manhã": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Ana Costa",
      "Bruno Souza",
      "Carlos Almeida",
      "Daniela Pereira",
      "Eduardo Santos",
    ],
  },
  "7° Ano manhã": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Felipe Martins",
      "Gabriela Rocha",
      "Hugo Lima",
      "Isabela Costa",
      "Juliana Ferreira",
    ],
  },
  "8° Ano manhã": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Larissa Souza",
      "Marcos Silva",
      "Nathália Gomes",
      "Otávio Oliveira",
      "Paula Souza",
    ],
  },
  "9° Ano manhã": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Rafael Pereira",
      "Sofia Costa",
      "Thiago Almeida",
      "Vanessa Martins",
      "William Santos",
    ],
  },
};

export const salasMockTarde = {
  "6° Ano tarde": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Ana Costa",
      "Bruno Souza",
      "Carlos Almeida",
      "Daniela Pereira",
      "Eduardo Santos",
    ],
  },
  "7° Ano tarde": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Felipe Martins",
      "Gabriela Rocha",
      "Hugo Lima",
      "Isabela Costa",
      "Juliana Ferreira",
    ],
  },
  "8° Ano tarde": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Larissa Souza",
      "Marcos Silva",
      "Nathália Gomes",
      "Otávio Oliveira",
      "Paula Souza",
    ],
  },
  "9° Ano tarde": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Rafael Pereira",
      "Sofia Costa",
      "Thiago Almeida",
      "Vanessa Martins",
      "William Santos",
    ],
  },
  "1° Ano médio tarde": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Felipe Martins",
      "Gabriela Rocha",
      "Hugo Lima",
      "Isabela Costa",
      "Juliana Ferreira",
    ],
  },
  "2° Ano médio tarde": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Larissa Souza",
      "Marcos Silva",
      "Nathália Gomes",
      "Otávio Oliveira",
      "Paula Souza",
    ],
  },
  "3° Ano médio tarde": {
    professores: [
      "Ana Souza",
      "Carlos Silva",
      "João Pereira",
      "Luciana Almeida",
      "Luc",
      "Maria Silva",
      "Pedro Henrique",
      "Rafael Almeida",
    ],
    alunos: [
      "Rafael Pereira",
      "Sofia Costa",
      "Thiago Almeida",
      "Vanessa Martins",
      "William Santos",
    ],
  },
};
